### ISSUE TITLE
Could you make a tutorial video?

### ISSUE THREAD

**Issue by JasonDerulo1259** [charlypoirier/redditube#16]
I have absolutely no idea how to use this and genuinely didn't know it was coded in javascript for like 30 mins. Could you make a video tutorial on how to install/setup and use this?

**Comment by Engr-Solution** [comment]
> I have absolutely no idea how to use this and genuinely didn't know it was coded in javascript for like 30 mins. Could you make a video tutorial on how to install/setup and use this?
> 
> 

Same here 
A tutorial video on how to set it up would be nice 👍

**Comment by charlypoirier** [comment]
Hello,

I get that a full video tutorial would be useful for some people. But as a developer, the [README.md](https://github.com/charlypoirier/redditube#readme) should have everything you need to install and use the library in your projects and to start generating videos...

If you have more specific questions, maybe errors you've encountered... I would be happy to help you.
But I don't think I will be filming a video tutorial for it.
