### ISSUE TITLE
ffmpeg exited with code 1 || glitch.mp4: No such file or directory

### ISSUE THREAD

**Issue by Engr-Solution** [charlypoirier/redditube#17]
**Error: ffmpeg exited with code 1: C:\Users\user\Desktop\Projects\Redditube\node_modules\redditube\libs/../resources/videos/glitch.mp4: No such file or directory**

**Comment by Alex-Sour** [comment]
you dont have a glitch video resource
add one in

**Comment by Steve0929** [comment]
Had the same problem, for some reason I didn't have the `\node_modules\redditube\resources\videos` directory. To fix it I created it and added this video: https://github.com/charlypoirier/redditube/blob/master/resources/videos/glitch.mp4

**Comment by Engr-Solution** [comment]
Oh thanks @Alex-Sour 
Let me try it out
