### ISSUE TITLE
Request: Could you add support for Balabolka instead of Google Cloud TTS?

### ISSUE THREAD

**Issue by Alex-Sour** [charlypoirier/redditube#2]
So we don't have to have a billing account

**Comment by charlypoirier** [comment]
That's a great idea, I'll look into it. Thanks!

**Comment by Alex-Sour** [comment]
alright, thanks 👍

**Comment by charlypoirier** [comment]
Looks like Balabolka is only available on Windows, and I'd like it to work on Linux too...
It's hard to find a good offline text-to-speech library.

**Comment by charlypoirier** [comment]
I just changed the text-to-speech system, it sounds better now and doesn't require any external account.
