### ISSUE TITLE
Replacing background music (lofi1.mp3) results in error

### ISSUE THREAD

**Issue by Alex-Sour** [charlypoirier/redditube#6]
It would be better if it picked random music from the sounds folder instead of choosing just lofi1.mp3 every time
Deleted it and tried to replace it with other music, then waited like 30 minutes for my video to finish, only to have it crash at the very end.

**Comment by charlypoirier** [comment]
For now, it will always try to open `resources/sounds/lofi1.mp3`, so it should work if you correctly name your new music file `lofi1.mp3` and if it is longer than the video. I agree it would be better to pick a random file from `resources/sounds/`. I'll keep this issue open as well until I fix it.

Also, I know I'm not handling errors very well right now and Redditube can crash pretty easily, which is pretty annoying after waiting for minutes/hours.
