### ISSUE TITLE
RequestError: Error: Invalid URI "api/v1/access_token"

### ISSUE THREAD

**Issue by pgamerx** [charlypoirier/redditube#8]
RequestError: Error: Invalid URI "api/v1/access_token"     at new RequestError (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request-promise-core/lib/errors.js:14:15)     at Request.plumbing.callback (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request-promise-core/lib/plumbing.js:87:29)     at Request.RP$callback [as _callback] (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request-promise-core/lib/plumbing.js:46:31)     at self.callback (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:373:22)     at Request.emit (node:events:394:28)     at Request.init (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:443:17)     at Request.RP$initInterceptor [as init] (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request-promise-core/configure/request2.js:45:29)     at new Request (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:283:8)     at request (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/index.js:50:10)     at snoowrap.<anonymous> (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/index.js:141:14)     at snoowrap.credentialedClientRequest (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:217:47)     at snoowrap.updateAccessToken (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:264:17)     at /Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:83:18     at tryCatcher (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/util.js:16:23)     at Promise._settlePromiseFromHandler (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:547:31)     at Promise._settlePromise (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:604:18)     at Promise._settlePromise0 (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:649:10)     at Promise._settlePromises (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:729:18)     at Promise._fulfill (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:673:18)     at Promise._resolveCallback (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:489:14)     at Promise._settlePromiseFromHandler (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:559:17)     at Promise._settlePromise (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:604:18)     at Promise._settlePromise0 (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:649:10)     at Promise._settlePromises (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:729:18)     at Promise._fulfill (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:673:18)     at Timeout._onTimeout (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/timers.js:26:46)     at listOnTimeout (node:internal/timers:557:17)     at processTimers (node:internal/timers:500:7) {   cause: Error: Invalid URI "api/v1/access_token"       at Request.init (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:443:31)       at Request.RP$initInterceptor [as init] (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request-promise-core/configure/request2.js:45:29)       at new Request (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:283:8)       at request (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/index.js:50:10)       at snoowrap.<anonymous> (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/index.js:141:14)       at snoowrap.credentialedClientRequest (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:217:47)       at snoowrap.updateAccessToken (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:264:17)       at /Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:83:18       at tryCatcher (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/util.js:16:23)       at Promise._settlePromiseFromHandler (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:547:31)       at Promise._settlePromise (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:604:18)       at Promise._settlePromise0 (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:649:10)       at Promise._settlePromises (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:729:18)       at Promise._fulfill (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:673:18)       at Promise._resolveCallback (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:489:14)       at Promise._settlePromiseFromHandler (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:559:17)       at Promise._settlePromise (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:604:18)       at Promise._settlePromise0 (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:649:10)       at Promise._settlePromises (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:729:18)       at Promise._fulfill (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:673:18)       at Timeout._onTimeout (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/timers.js:26:46)       at listOnTimeout (node:internal/timers:557:17)       at processTimers (node:internal/timers:500:7),   error: Error: Invalid URI "api/v1/access_token"       at Request.init (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:443:31)       at Request.RP$initInterceptor [as init] (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request-promise-core/configure/request2.js:45:29)       at new Request (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/request.js:283:8)       at request (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/index.js:50:10)       at snoowrap.<anonymous> (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/request/index.js:141:14)       at snoowrap.credentialedClientRequest (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:217:47)       at snoowrap.updateAccessToken (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:264:17)       at /Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/snoowrap/dist/request_handler.js:83:18       at tryCatcher (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/util.js:16:23)       at Promise._settlePromiseFromHandler (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:547:31)       at Promise._settlePromise (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:604:18)       at Promise._settlePromise0 (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:649:10)       at Promise._settlePromises (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:729:18)       at Promise._fulfill (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:673:18)       at Promise._resolveCallback (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:489:14)       at Promise._settlePromiseFromHandler (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:559:17)       at Promise._settlePromise (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:604:18)       at Promise._settlePromise0 (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:649:10)       at Promise._settlePromises (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:729:18)       at Promise._fulfill (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/promise.js:673:18)       at Timeout._onTimeout (/Users/navdeepsharma/Desktop/Reddit Video Maker/node_modules/bluebird/js/release/timers.js:26:46)       at listOnTimeout (node:internal/timers:557:17)       at processTimers (node:internal/timers:500:7),   options: {     form: {       grant_type: 'password',       username: 'confidential',       password: 'confidential'     },     uri: 'api/v1/access_token',     method: 'POST',     baseUrl: 'https://www.reddit.com',     headers: { 'user-agent': 'PGamerX' },     auth: {       user: 'confidential',       pass: 'confidential'     },     json: true,     gzip: true,     callback: [Function: RP$callback],     tunnel: false,     transform: undefined,     simple: true,     resolveWithFullResponse: false,     transform2xxOnly: false   },   response: undefined }

**Comment by pgamerxdev** [comment]
@charlypoirier I havent changed the code a bit, it worked fine 1 month back.
Today I decided to rerun but it didnt

**Comment by charlypoirier** [comment]
I just tried generating a video (been a while) and everything worked.

The error you're getting seems to come from [snoowrap](https://github.com/not-an-aardvark/snoowrap), the library Redditube uses to communicate with Reddit.
I found [someone having the same issue](https://www.reddit.com/r/redditdev/comments/7qh4tp/error_invalid_uri_apiv1access_token_when_using/) (4 years ago) but without much more information. So I'm not sure why that happens.

#### What you can try
- Make sure you have the correct credentials, [there](https://www.reddit.com/prefs/apps).
- If you are using a `refresh_token`, try using your Reddit `username` and `password` instead.
- Try reinstalling dependencies.
```bash
$ rm -r node_modules/
$ npm install
```
- Try using another Node.js version (I use Node.js v16.6.0 now, but used older versions in the past without any problems).
